export const safeWords = [
    "jesus is a biscuit let him sop me up",
    "lipsync for your life",
    "mother dust",
    "your dad just calls me Katya",
    "big red scare with the long blonde hair",
    "UNHhhh",
    "chunky yet funky",
    "good god get a grip girl",
    "go back to party city where you belong",
    "no tea no shade no pink lemonade",
    "sip some tea",
    "throw some shade",
    "this isn't Rupaul's best friend race",
    "America's next drag superstar",
    "oh, at all",
    "hiiieeeeeeeeeeeeeee",
    "my name is Roxxxy Andrews and I'm here to make it clear",
    "I'd like to keep it on please",
    "serving",
    "party",
    "the library is open",
    "read u wrote u",
    "category is",
    "kiki",
    "look at huh",
    "hey qween",
    "oh pit crew",
    "may I call you jiggly",
    "covergirl",
    "put the bass in that walk",
    "head to toe let your whole body talk",
    "lacefront",
    "death drop",
    "tongue pop",
    "y'all wanted a twist, eh",
    "wig reveal",
    "Paris is burning",
    "realness",
    "water off a duck's back",
    "tuck",
    "shake n' go wigs",
    "bring back my girls",
    "thwoorp",
    "you better work",
    "padding",
    "**rosepetals**",
    "be the strange you wish to see in the world",
    "gender is a construct tear it apart",
    "squirrel friends",
    "if you're not wearing heels you're not doing drag",
    "this is my hair",
    "I don't wear wigs",
    "purse first",
    "you're perfect, you're beautiful, you look like Linda Evangelista",
    "Valentina your smile is beautiful",
    "fan favorite",
    "call me mother",
    "reading is fundatmental",
    "just between us girls",
    "it's monsoon season",
    "condragulations",
    "cucu",
    "yas gawd",
    "untucked",
    "shantay you stay",
    "sashay away",
    "eleganza",
    "toot",
    "boot",
    "sickening",
    "the time has come",
    "I feel very attacked",
    "donut come for me",
    "okurrrrrr",
    "fierce",
    "back rolls",
    "oh honey",
    "not today, Satan",
    "same parts",
    "because what you see isn't always the truth",
    "Being In Total Control of Herself",
    "glamazon",
    "fishy",
    "d to the e to the t to the o to the hold up...x",
    "bring it to the runway",
    "oh no she better don't",
    "now prance, prance I say",
    "herstory",
    "unclockable",
    "your makeup is terrible",
    "radical, magical, liberal art",
    "the body is here",
    "hog body",
    "what category are we on right now",
    "shook",
    "voguing",
    "Rolaskatox",
    "henny",
    "we're all born naked and the rest is drag",
    "jealous of my boogie",
    "because I'm what - sickening",
    "because you are not that king of girl",
    "I don't have a sugar daddy, I've never had a sugar daddy",
    "lipsync assassin",
    "champagne and red M&amp;M's",
    "miss vaaaaaaaaanjie",
    "gagging",
  ];
  
  
export const nsfw = [
    "if you can't love yourself how in the hell you gonna love anybody else can I get an amen up in here",
    "hunty",
    "I'm not joking, bitch",
    "and don't fuck it up",
    "snatch game",
    "kaikai",
    "step your pussy up",
    "get those nuts away from my face",
    "tired-ass showgirl",
    "charisma, uniqueness, nerve and talent",
    "gagging",
    "the only high class Russian whore",
    "fuck my pussy with a rake, Mom",
    "I was raised by wolves bitch",
  ];